DROP TABLE IF EXISTS "uppers";
CREATE TABLE "uppers" ("word" VARCHAR(255) NOT NULL DEFAULT "", "description" VARCHAR(255) NOT NULL  DEFAULT "");

INSERT INTO "uppers" ("word", "description") VALUES ("alr", "American Law Reports");
INSERT INTO "uppers" ("word", "description") VALUES ("amt", "Amount");
INSERT INTO "uppers" ("word", "description") VALUES ("api", "Application Programming Interface");
INSERT INTO "uppers" ("word", "description") VALUES ("cdn", "Content Delivery Network");
INSERT INTO "uppers" ("word", "description") VALUES ("crbt", "Caller's Ring Back Tone");
INSERT INTO "uppers" ("word", "description") VALUES ("crud", "Create, Read, Update, Delete - operations");
INSERT INTO "uppers" ("word", "description") VALUES ("css", "Cascading Style Sheets");
INSERT INTO "uppers" ("word", "description") VALUES ("db", "Database");
INSERT INTO "uppers" ("word", "description") VALUES ("dob", "Date of Birth");
INSERT INTO "uppers" ("word", "description") VALUES ("dod", "Date of Death (died on)");
INSERT INTO "uppers" ("word", "description") VALUES ("faq", "Frequently Asked Questions");
INSERT INTO "uppers" ("word", "description") VALUES ("ftp", "File Transfer Protocol");
INSERT INTO "uppers" ("word", "description") VALUES ("gpa", "Grade Point Average");
INSERT INTO "uppers" ("word", "description") VALUES ("html", "Hyper Text Markup Language");
INSERT INTO "uppers" ("word", "description") VALUES ("http", "Hyper Text Transmission Protocol");
INSERT INTO "uppers" ("word", "description") VALUES ("iata", "International Air Transport Association");
INSERT INTO "uppers" ("word", "description") VALUES ("ic", "Identity Card");
INSERT INTO "uppers" ("word", "description") VALUES ("icao", "International Civil Aviation Organization");
INSERT INTO "uppers" ("word", "description") VALUES ("id", "Identity Number");
INSERT INTO "uppers" ("word", "description") VALUES ("im", "Chat IDs and Instant Messaging");
INSERT INTO "uppers" ("word", "description") VALUES ("ip", "Internet Protocol (Address)");
INSERT INTO "uppers" ("word", "description") VALUES ("irc", "Internet Relay Chat");
INSERT INTO "uppers" ("word", "description") VALUES ("isbn", "International Standard Book Number");
INSERT INTO "uppers" ("word", "description") VALUES ("isp", "Internet Service Provider");
INSERT INTO "uppers" ("word", "description") VALUES ("mime", "Multipurpose Internet Mail Extensions");
INSERT INTO "uppers" ("word", "description") VALUES ("msn", "Microsoft Network");
INSERT INTO "uppers" ("word", "description") VALUES ("nric", "National Registration Identity Card (Singapore)");
INSERT INTO "uppers" ("word", "description") VALUES ("ns", "Name Server");
INSERT INTO "uppers" ("word", "description") VALUES ("pan", "Permanent Account Number");
INSERT INTO "uppers" ("word", "description") VALUES ("pc", "Piece");
INSERT INTO "uppers" ("word", "description") VALUES ("pcs", "Pieces");
INSERT INTO "uppers" ("word", "description") VALUES ("pdf", "PDF document");
INSERT INTO "uppers" ("word", "description") VALUES ("pk", "Primary Key");
INSERT INTO "uppers" ("word", "description") VALUES ("poc", "Proof Of Concet, Point Of Contact");
INSERT INTO "uppers" ("word", "description") VALUES ("prbt", "Personalised Ring Back Tone");
INSERT INTO "uppers" ("word", "description") VALUES ("qr", "Quick Response Code");
INSERT INTO "uppers" ("word", "description") VALUES ("qty", "Quantity");
INSERT INTO "uppers" ("word", "description") VALUES ("rgb", "Red Green Blue");
INSERT INTO "uppers" ("word", "description") VALUES ("smtp", "Simple Mail Transfer Protocol");
INSERT INTO "uppers" ("word", "description") VALUES ("sn", "Serial Number");
INSERT INTO "uppers" ("word", "description") VALUES ("sql", "SQL");
INSERT INTO "uppers" ("word", "description") VALUES ("toc", "Table of Contents");
INSERT INTO "uppers" ("word", "description") VALUES ("uri", "Uniform Resource Index");
INSERT INTO "uppers" ("word", "description") VALUES ("url", "Uniform Resource Locator");
INSERT INTO "uppers" ("word", "description") VALUES ("vat", "Value Added Tax");
INSERT INTO "uppers" ("word", "description") VALUES ("xml", "Extensible Markup Language (XML)");
INSERT INTO "uppers" ("word", "description") VALUES ("xref", "Cross Reference, generally a URL");
INSERT INTO "uppers" ("word", "description") VALUES ("zip", "Zone Improvement Planning");